import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

let buildNum = 0;
try { buildNum = parseInt(readFileSync(join(root, 'build-number'), 'utf8').trim(), 10) || 0; } catch {}

const content = `// Auto-generated by scripts/generate-version.mjs — do not edit
export const FRAMEWORK_VERSION = '${pkg.version}';
export const BUILD_COUNT = ${buildNum};
`;

writeFileSync(join(root, 'src/version.ts'), content, 'utf8');
console.log(`Generated version.ts: v${pkg.version} build #${buildNum}`);