import { readFileSync, writeFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

let buildNum = 0;
const numPath = join(root, '.buildnum');
if (existsSync(numPath)) {
  buildNum = parseInt(readFileSync(numPath, 'utf8').trim(), 10) || 0;
}

const content = `// Auto-generated by scripts/generate-version.mjs — do not edit
export const FRAMEWORK_VERSION = '${pkg.version}';
export const BUILD_NUMBER = ${buildNum};
`;

const outPath = join(root, 'src/version.ts');
writeFileSync(outPath, content, 'utf8');
console.log(`Generated version.ts: v${pkg.version} build #${buildNum}`);